version: '3'

services:
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend1
      - backend2
      - backend3
    volumes:
      - ./configs:/app/configs

  backend1:
    image: jmalloc/echo-server
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - RESPONSE_PREFIX=Backend 1

  backend2:
    image: jmalloc/echo-server
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - RESPONSE_PREFIX=Backend 2

  backend3:
    image: jmalloc/echo-server
    ports:
      - "8083:8080"
    environment:
      - PORT=8080
      - RESPONSE_PREFIX=Backend 3